# Generated by Django 5.0.3 on 2024-03-17 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0002_alter_partner_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='document',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
